name: Scheduled Scrape

on:
  schedule:
    - cron: '0 16,22 * * *'  # Runs every day at 16:00 and 22:00 UTC
  workflow_dispatch:         


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2


      - name: Run Python script
        run: python your_script.py
