name: Scheduled Scrape

on:
  schedule:
    - cron: '0 16,22 * * *'  # Runs every day at 16:00 and 22:00 UTC
  workflow_dispatch:

env:
  DATE: ${{ format('yyyy-MM-dd', github.run_started_at) }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '138'

      - name: Remove old ChromeDriver
        run: |
          sudo rm -f /opt/hostedtoolcache/setup-chrome/chromedriver/**/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run web scraper
        run: python web_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data_directory/*.csv
          git commit -m "Add snapshot CSV for water supply scrape"
          git push
