name: Scheduled Scrape

on:
  schedule:
    - cron: '0 16,22 * * *'  # Runs every day at 16:00 and 22:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '138'
          install-chromedriver: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Chrome & ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run web scraper
        run: python web_scraper.py