name: Scheduled Scrape

on:
  schedule:
    - cron: '0 16,22 * * *'  # Runs every day at 16:00 and 22:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome & matching ChromeDriver
        run: |
          # Install Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"

          # Extract major version (e.g. 114 from 114.0.5735.90)
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
          echo "Chrome major version: $CHROME_MAJOR_VERSION"

          # Fetch matching chromedriver version
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")
          echo "Matching ChromeDriver version: $DRIVER_VERSION"

          # Download and install chromedriver
          wget -q https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify installation
          chromedriver --version

      - name: Verify Chrome & ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run web scraper
        run: python web_scraper.py